### ISSUE TITLE
logout's url parameter should be 'service' not 'url'

### ISSUE THREAD

**Issue by hrool** [mingchen/django-cas-ng#100]
pip install django-cas-ng 
after i logout , i find url like this cas/logout?url=http
and the redirect did not working,
after i change the 'url' to 'service'  like: cas/logout?service=http
it work!.
if this is really a bug, can fix it? or i could try to fix it .

**Comment by nitmir** [comment]
You then should use CASv3 and not CASv1 or v2. As it can be seen on https://github.com/python-cas/python-cas/blob/master/cas.py, for CASv1 and v2 the logout redirect parameter name is url, and for CASv3 service. django-cas-ng use python-cas for CAS client operations.

**Comment by hrool** [comment]
@nitmir 
thank you, i use CAS_VERSION = 3 in settings.py. it works for me, redirect work fine.
but the README.rst file said:
CAS_VERSION: The CAS protocol version to use. '1' and '2' are supported, with '2' being the default.
dose '3' is not support, or README.rst is out of date?

**Comment by nitmir** [comment]
README is out of date, CAS v3 is supported.
