### ISSUE TITLE
ImportError - lxml

### ISSUE THREAD

**Issue by michaelsteigman** [mingchen/django-cas-ng#110]
We've just set up django-cas-ng (v3.5.6) and are seeing the following exception. 

`ImportError: No module named 'lxml'
(4 additional frame(s) were not displayed)
...
  File "django_cas_ng/views.py", line 48, in login
    clean_sessions(client, request)
  File "django_cas_ng/views.py", line 155, in clean_sessions
    for slo in client.get_saml_slos(request.POST.get('logoutRequest')):`

Looks like there is no reference to `lxml` in django-cas-ng and the reference is actually in python-cas. I am new to the Django packaging process but it seems as though python-cas ought to have `lxml` in its setup.py. Is that correct or are we doing something wrong?

**Comment by mingchen** [comment]
closed due to in-active.
