### ISSUE TITLE
not work with iframe when logout

### ISSUE THREAD

**Issue by duke2012** [mingchen/django-cas-ng#111]
seems that when i embed cas log in page with iframe, it does not work when do cas log out from other page which share same cas server.

**Comment by danizen** [comment]
@duke2012, I recommend you use something like Chrome Devtools Network tab to trace what is happening.   My theory would be that the other frame is not reloaded.  It would also be helpful to know what browser this is, and if it is a site that anyone can play with.

**Comment by wangyouyan** [comment]
Exception Location: 	/usr/lib/python2.7/site-packages/django_cas_ng/utils.py in get_service_url, line 45

**Comment by danizen** [comment]
@wangyouyan, can you provide more data on how this is reproduced?   What is the sequence of web  requests before the exception is thrown?  I will test get_service_url() with some complicated URLs and see when, if ever, it throws.

**Comment by wangyouyan** [comment]
@danizen I'm sorry for that,It might be relate to my env.It might encounter this issue when the django's version is 1.10.By the way,I met another issue,When I access url "http://www.example.com/accounts/login",the brower return 404([22/Mar/2017 12:49:32]"GET / HTTP/1.1" 404 2332).
But "http://www.example.com/accounts/logout" & "http://www.example.com/accounts/callback", are normal.That's weird.

**Comment by danizen** [comment]
@wangyouyan, what CAS settings do you have in your settings file?

For example, my base settings file has:

```python
CAS_CREATE_USER = False

CAS_SERVER_URL = 'https://login-prod.nlm.nih.gov/cas/'
```

I can test CAS manually by manually entering the following URL in my browser:

```
https://login-prod.nlm.nih.gov/cas/login?service=https%3a%2f%2fnlmcatutil.nlm.nih.gov%2faccounts%2flogin
```

I get the service parameter by going to https://urlencode.org/ and entering the URL.  This way I skip the process of CAS redirecting to this site and simply take it from that point.

I can get something like the same thing using the Network tab of Chrome Developer Tools, but it isn't always easy.

**Comment by mingchen** [comment]
close due to inactive.
