### ISSUE TITLE
Setting to change url_suffix

### ISSUE THREAD

**Issue by Hugodby** [mingchen/django-cas-ng#112]
Hello,

I'm using your plugin on a project using my school CAS (INSA Lyon). They changed the default url to call for the CAS V3 like that : `https://login.insa-lyon.fr/cas/p3/serviceValidate`. 
The workaround I use is to edit `url_suffix` (line 208) from cas.py of python-cas : https://github.com/python-cas/python-cas/blob/master/cas.py#L208

Is it possible to make that configurable ? I can do the implementation if you guide me a little bit.

Thank you very much.

**Comment by intgr** [comment]
I had the same issue. I think the URL actually *shouldn't* be configurable. The CAS spec is clear that v3 clients should always access `p3/serviceValidate`, see https://apereo.github.io/cas/5.0.x/protocol/CAS-Protocol-Specification.html#2-cas-uris

I have created a pull request for python-cas: https://github.com/python-cas/python-cas/pull/5
