### ISSUE TITLE
No superusers

### ISSUE THREAD

**Issue by tayapski** [mingchen/django-cas-ng#113]
I'm using django-cas-ng version 3.5.4 as a CAS client on a Django 1.6.10 client. The CAS client can receive the attributes from the CAS server just fine including is_superuser, and is_staff. The problem is this doesn't seem to be reflected on the user on the CAS client side.

**Comment by pbaehr** [comment]
I needed this too. I just submitted a pull request which makes this fairly straightforward (https://github.com/mingchen/django-cas-ng/pull/123).

If it doesn't get merged you can check out how I solved it for my project on my fork:
https://github.com/pbaehr/django-cas-ng

**Comment by bgroff** [comment]
I think a fix for this issue has been merged in PR #125
