### ISSUE TITLE
Fix for bad upstream encodings/decodings

### ISSUE THREAD

**Issue by danizen** [mingchen/django-cas-ng#114]
I have a problem here at the U.S. National Library of Medicine.    Our CAS server is protected by a CA SiteMinder httpd module that supports NIH wide login.   When the user chooses the PIV login (using a PIV card), the encoding of the service parameter gets mangled a bit.   So it goes like this:

* Django redirects to CAS with correct service URL
* CAS redirects to NIH Login with deeply encoded target including service URL
* NIH Login redirects to page that uses ActiveX and/or other technologies to validate PIV card
* This page redirects directly to CAS, with incorrectly encoded service URL
* CAS generates ticket for incorrect service URL
* Django fixes it
* django-cas-ng attempts to validate ticket, which fails

I'm thinking a way of fixing this (for me) is with a setting parameter that asks django-cas-ng to store the next page as a cookie, so that the service parameter presented to CAS includes only one level of encoding.

Generally, there should be no difference between service=https://casprotected.example.com/accounts/login?next=/admin and service=https://casprotected.example.com/accounts/login

Having explained the issue, I'll start working on a fix and see if you will accept a pull request.

**Comment by danizen** [comment]
In my environment, this works if I set `CAS_RETRY_LOGIN = True`.   I still want to do a fix, because all the service validation errors show up on a dashboard for the CAS Administrator.   He says he is OK wit hthis, but... so, I'm working on a pull that will support a `CAS_STORE_NEXT` parameter which will store the page in the session.

**Comment by mingchen** [comment]
Fixed by [pull #117](https://github.com/mingchen/django-cas-ng/pull/117)
