### ISSUE TITLE
Delete multiple session tickets on logout

### ISSUE THREAD

**Issue by shacker** [mingchen/django-cas-ng#120]
In logout():

`st = SessionTicket.objects.get(session_key=request.session.session_key)`

This has been fine for us for a year+ (never noticed it), but we recently changed some session settings and some users who had been logged in for a long time apparently ended up with two sessions. When they tried to log out, they triggered error `get() returned more than one SessionTicket - it returned 2!`. Even though this line is in a try/except, the Django-level error is still triggered. And these users could not log out. I had to manually empty the `django_sessions` table to fix it. 

Would it be worth patching this to handle `MultipleObjectsReturned` in addition to `SessionTicket.DoesNotExist` ? Or is this just a weird edge case?

**Comment by mingchen** [comment]
close due to inactive.
