### ISSUE TITLE
django_cas_ng throws ssl error

### ISSUE THREAD

**Issue by arun1809** [mingchen/django-cas-ng#126]
Facing weird SSL error with django CAS client when login request redirecting to remote CAS server(with https) for authentication. But I see remote CAS server is generating ticket when tried login. Im not sure whether its failing while request or response.

	Traceback (most recent call last):
	 File "/home/test/p36d19/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 438, in wrap_socket
	   cnx.do_handshake()
	 File "/home/test/p36d19/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1638, in do_handshake
	   self._raise_ssl_error(self._ssl, result)
	 File "/home/test/p36d19/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1378, in _raise_ssl_error
	   _raise_current_error()
	 File "/home/test/p36d19/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
	   raise exception_type(errors)
	OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

and settings file has

	INSTALLED_APPS = (
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'django_cas_ng',
	)
	AUTHENTICATION_BACKENDS = (
	   'django.contrib.auth.backends.ModelBackend',
	   'django_cas_ng.backends.CASBackend',
	)
	CAS_SERVER_URL = "https://login.cas-example.com:8443/cas/login"
	CAS_REDIRECT_URL = '/login_test'

I'm running django app using runsslserver (port 3000) with self-certificate (and tried with the server's certificate too) in my development machine.

No luck even after setting following env variable (there is some bug in requests module with SSL library)

REQUESTS_CA_BUNDLE='\tmp\app.crt'

**Comment by mingchen** [comment]
you need a valid ssl certifcate, not self signed. you can get a free one like from Letscrypt.
