### ISSUE TITLE
Update readme to warn  programmers who use old version of the library

### ISSUE THREAD

**Issue by marcosthejew** [mingchen/django-cas-ng#133]
I think you should warn on the readme file that programmers updating the library that use a custom backend should also change their authneticate method header to: "def authenticate(self, request, ticket, service):" to adjust to commit  d56247114f7b652f365b9e4773532bb2293c5cea. Otherwise their app will break like ours did on update.

**Comment by mingchen** [comment]
Thanks for report. If you like to send a pull request for this I would like to merge it.

**Comment by mingchen** [comment]
close due to inactive.
