### ISSUE TITLE
Adding `request` to logout signal params

### ISSUE THREAD

**Issue by zaadeh** [mingchen/django-cas-ng#135]
In accordance with `django.contrib.auth` logout signal, can you consider passing `request` object to signal receiver?

My use case is in my current project I depend on a session variable to keep track of which auth backend authenticated the current user using login and logout signals. So I would need the request object in my logout handler (to access the `request.session` object), in addition to login handler to make this work.

`request` object would also be useful if I want to add `logout(request)` in the signal handler to completely log the user out.

related lines would be views.py:116, 166.

Thanks in advance.

**Comment by mingchen** [comment]
Closed due in-active.
