### ISSUE TITLE
Adding `backend` param to call to `django.contrib.auth.login()`

### ISSUE THREAD

**Issue by zaadeh** [mingchen/django-cas-ng#136]
Django depends on the optional param `backend` on call to `login()` to set the authenticator backend on the session and keeping it's reference for later use. If a backend does not pass this param, but is listed in `settings.AUTHENTICATION_BACKENDS`, it tries to put the module path instead. But if I want to use this backend manually (without listing it in backends), I would have a problem later finding which auth backend were used for this user. So I ask to add this param.

Related line would be views.py: 70

Thanks.

**Comment by mingchen** [comment]
Closed due in-active.
