### ISSUE TITLE
meet `request.user.is_authenticated()` is a property not a funtion bug & miss `on_delete` property in `ProxyGrantingTicket`

### ISSUE THREAD

**Issue by zhongqin0820** [mingchen/django-cas-ng#144]
version: django-cas-ng (3.5.8)
python version: 3.6.3
pip version: 9.0.1
platform: win10

**Comment by zhongqin0820** [comment]
just change `request.user.is_authenticated()`  into `request.user.is_authenticated`
and add property `on_delete` in `ProxyGrantingTicket` will solve this.

**Comment by mingchen** [comment]
Fixed by PR #143
