### ISSUE TITLE
Review PR and release new version

### ISSUE THREAD

**Issue by bgroff** [mingchen/django-cas-ng#147]
@mingchen I have submitted a PR that fixes some minor issues with Django 2.0. I was wondering if you could review those changes and if you are happy, merge the PR. If we could push a new release as well that would be great.

**Comment by mingchen** [comment]
v3.5.9 was released.

**Comment by bgroff** [comment]
Thanks!

**Comment by bgroff** [comment]
Was there an issue with the 3.5.9 release? I cannot seem to find it on pypi anymore.
