### ISSUE TITLE
Can I share authentication across two sites from a single login?

### ISSUE THREAD

**Issue by philsheard** [mingchen/django-cas-ng#151]
I have a demo project running [1] to test shared login across multiple clients. Server is [jbittel/django-mama-cas](https://github.com/jbittel/django-mama-cas) and clients are running vanilla [mingchen/django-cas-ng](https://github.com/mingchen/django-cas-ng).

Both clients can authenticate fine, but logging into one then forces a logout on the other. I want to be able to move between different sites (one for frontend, one for backend) based on a single login. A roundtrip to the CAS server with some sort of authentication token would be fine, so long as the user doesn't have to keep logging in to each one.

Any advice or experience?

[1] https://github.com/philsheard/django-cas-test

**Comment by danizen** [comment]
This may have something to do with the configuration of these.   If you are running them on different domains, e.g. "client-cas.local" and "second-cas.local", then you should be fine, but when you are running both on localhost, e.g. with different ports, then the sessionid cookie written by one client will overwrite the sessionid cookie written by the other client.

The other piece of configuration to consider is whether you want the session to be shared.   You would then need to have multiple databases, and a routing manager (I think that's what they're called) to say that the sessions, users, and django_cas_ng SessionTicket models be stored in the authentication database.   If you do this, and manipulate the domain on the session cookie, you could accomplish single login to both applications (e.g. without hidden redirects to the CAS server).

An easier way to do that may be to investigate the Django sites framework - https://docs.djangoproject.com/en/2.0/ref/contrib/sites/

**Comment by mingchen** [comment]
Closed due in-active.
