### ISSUE TITLE
Update last release in PyPI

### ISSUE THREAD

**Issue by nsurbay** [mingchen/django-cas-ng#152]
Hello,

It's seem that the last release 3.5.9 was not update on [PyPI](https://pypi.python.org/pypi/django-cas-ng) repository. It's not possible to get the last release with `pip install --upgrade django-cas-ng`

Can you update the version ?

Thank you

**Comment by grahamu** [comment]
Hi @mingchen, Django 2.0 compatibility is not possible until the latest release is published to PyPi. Please publish 3.5.9, thanks!

**Comment by grahamu** [comment]
@bgroff I wonder if you might publish the latest release (v3.5.9 from January 2, 2018) to PyPi? We're looking for Django 2.0 compatibility. Thanks!

**Comment by bgroff** [comment]
@mingchen is the only person (that I know of), that can publish to PyPI. There was an issue with the initial 3.5.9 release, but I think that all of those issues have been resolved.

While not idea, you can always use: pip install https://github.com/mingchen/django-cas-ng/archive/master.zip to install the latest code.

**Comment by grahamu** [comment]
Thanks for that information @bgroff, much appreciated. We're eagerly looking forward to the next published release for Django 2.0 support!

**Comment by mingchen** [comment]
Sorry for late response. The last push to pypi failed to pypi migration, old API is not supported, need upgrade to new API.
3.5.9 have been publish with newer pypi API.
