### ISSUE TITLE
Redirect attacks with /accounts/login

### ISSUE THREAD

**Issue by danizen** [mingchen/django-cas-ng#153]
One of our applications using django-cas-ng uses Django's login to authenticate the old ColdFusion admin system.   Functionality is slowly being moved into Django, with Django in charge of login and everything that's been implemented in Django.

This exposes the next pointer's ability to handle a non-relative URI to our security scanners, which point out that being able to do https://example.com/accounts/login/?next=http://google.com/ could be considered a security issue.

I have two questions:
* Anything built-into django-cas-ng that could white list host names?
* If not, would this make sense as a feature request:
   - Use `ALLOWED_HOSTS` to validate the next pointer, assuming that validating the relative 
      URI is the business of the back-end site following redirect.
   - If `CAS_ALLOWED_HOSTS` is not None, then append `CAS_ALLOWED_HOSTS` before calling `is_safe_url` provided by django.

This would alter some code in the login view:

```python
    # Validate the next pointer, if it appears in the URL.
    if next_page:
        cas_allowed_hosts = list(settings.ALLOWED_HOSTS)
        if settings.CAS_ALLOWED_HOSTS:
            cas_allowed_hosts += settings.CAS_ALLOWED_HOSTS
        if not is_safe_url(next_page, allowed_hosts=cas_allowed_hosts):
            raise DisallowedRedirect()
```

My principal question is whether this goes to far, and whether there are folks out there who want `/accounts/login` to be less strict.   I propose this because Django is batteries included, and things should be "safe by default".   I've already patched our wrapper login view with similar code, and am asking whether I should contribute to the more general package.

**Comment by mingchen** [comment]
What is security issue if `next` point to other domain? it is design to support any domain, `next` can validate token with SSO server. this is how SSO works. 
see https://github.com/mingchen/django-cas-ng/blob/master/docs/CAS%20Protocol%20%20Introduction.docx

You can add whitelist for `next` domain to enhance security to only allow specific apps.

**Comment by danizen** [comment]
I am just passing on security issue identified by IBM AppScan.  Our CAS server validates the domain in service only, but you are right that validating the next pointer would be possible in CAS server.
