### ISSUE TITLE
CAS middleware missing in the ReadMe

### ISSUE THREAD

**Issue by mpibpc-mroose** [mingchen/django-cas-ng#157]
Hi,
in your Readme yo suppose to include the Middleware in the Django settings. But the example configuration is lacking this.

**Comment by syserr0r** [comment]
For what it is worth I intentionally do not use the middleware and appear to suffer no ill effects.

I am not interested in using CAS for admin login and I provide both django built-in authentication as well as CAS authentcation to users so overriding the default login/logout pages may not be desirable (depending on how it is done, I have not tested this).

**Comment by mingchen** [comment]
Closed due in-active.
