### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by CharlesQQ** [mingchen/django-cas-ng#158]
File "C:\python3.6\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 25, column 4880

**Comment by bgroff** [comment]
Without any more context, I am afraid no one will be able to help you with your issue.

**Comment by manutheking** [comment]
I'm having this error on production but not in local, any clue on this?

**Comment by david-house-harvard** [comment]
I encountered this issue and was able to isolate it to an updated dependency, `python-cas`. Our authentication works with the version lock `python-cas==1.2.0` but breaks when the lock is removed and `django-cas-ng` installs `python-cas==1.3.0`. Hopefully this workaround is helpful to you @manutheking 

I didn't have any more time to investigate the issue, unfortunately. If I can get the time, I will post my findings here.

**Comment by mingchen** [comment]
Closed due in-active.
