### ISSUE TITLE
CAS_ADMIN_PREFIX does not redirext to cas login

### ISSUE THREAD

**Issue by tehmanu** [mingchen/django-cas-ng#163]
Hello,

I've been having some issues trying to get the admin authentication made by CAS, or at least redirect the /app/admin/login to /app/login where it does authenticate with CAS.

As README says:

> CAS_ADMIN_PREFIX: The URL prefix of the Django administration site. If undefined, the CAS middleware will check the view being rendered to see if it lives in django.contrib.admin.views.

I understand that setting _CAS_ADMIN_PREFIX_ to /app/admin/ or /app/admin/login, makes the admin login use CAS.

Even with the var set, /app/admin redirects to /app/admin/login default login page.

**Comment by Jiloc** [comment]
did you find a work around? same problem here

**Comment by manutheking** [comment]
yes, had to override the site admin, this is my response from another account 

https://stackoverflow.com/questions/51652452/using-django-cas-ng-to-authenticate-on-admin-site

**Comment by duoi** [comment]
Was this happening even after having the `django_cas_ng.middleware.CASMiddleware` middleware in place?

**Comment by leavest** [comment]
> Was this happening even after having the `django_cas_ng.middleware.CASMiddleware` middleware in place?

my settings.py
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',

    'django_cas_ng',
    # 跨域访问
    'corsheaders',
]
...
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 跨域访问
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django_cas_ng.middleware.CASMiddleware',

]

# 使用自定义后台auth认证方法
AUTHENTICATION_BACKENDS = (
    'django_cas_ng.backends.CASBackend',
)

# cas 配置
CAS_ADMIN_PREFIX = 'admin'
```

my urls.py 
```
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('login/?$', django_cas_ng.views.LoginView.as_view(), name='cas_ng_login'),
    re_path('logout/?$', django_cas_ng.views.LogoutView.as_view(), name='cas_ng_logout'),
]
```

logout action
![image](https://user-images.githubusercontent.com/30454841/49855439-41bf4080-fe28-11e8-91cf-6902895ec242.png)
> 
login action
![image](https://user-images.githubusercontent.com/30454841/49855508-6ddac180-fe28-11e8-9f85-4d083ff945b2.png)

it does not redirect to cas/login page

How do I configure?
