### ISSUE TITLE
Specifying CAS_RENAME_ATTRIBUTES that do not change effectively removes them

### ISSUE THREAD

**Issue by syserr0r** [mingchen/django-cas-ng#172]
For example, with:
``` python
CAS_RENAME_ATTRIBUTES = {
    "first_name": "first_name",
    "last_name": "last_name",
    "email": "email",
}
```
This code in `django-cas-ng` will effectively remove any "first_name", "last_name" and "email" attributes that are passed: https://github.com/mingchen/django-cas-ng/blob/82305a0fc0f82c4f1910c662807ad9384e9e832d/django_cas_ng/backends.py#L36-L41

This may be desirable, in which case it should be documented (as I did not initially understand why the attributes were not populating).

If not, changing the `if`-line to this should suffice (or removing the `pop()` -- I'm not sure if it is needed as superfluous attributes would just be ignored wouldn't they?)
 ``` python
 if cas_attr_name in attributes and req_attr_name is not cas_attr_name:
```

**Comment by duoi** [comment]
I agree that this should probably be addressed, but I'm curious as to your reason for doing this in the first place hah.

This is pretty low-hanging fruit, would you like to fix it and submit a PR?

**Comment by syserr0r** [comment]
Sure, I wasn't sure if you wanted to leave it in as possibly desirable behaviour and document (such as to suppress an unwanted attribute) or fix, and if fix then do you want to keep the original attributes when renaming (so more like aliasing) or remove the original attribute when renaming?

I was trying to get attributes pulled through and I ended up with the example above when troubleshooting.

**Comment by syserr0r** [comment]
I have provided two PRs, one which keeps the old name another that does not. If you would prefer to keep the 'feature' then I can whip up a change to the docs instead -- just let me know.
