### ISSUE TITLE
Support the 'signed_cookies' Session Engine

### ISSUE THREAD

**Issue by bramwelt** [mingchen/django-cas-ng#174]
Due to the limitation on session data (255 varchars), the signed cookies session backend can't be used with Django CAS NG.

**Comment by mbaechtold** [comment]
We worked around this by creating a migration:

```
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("django_cas_ng", "0001_initial"), ("myap", "0001_initial")]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE django_cas_ng_sessionticket" " ALTER COLUMN session_key" " TYPE varchar(1024);"
        )
    ]
```

**Comment by nikolas** [comment]
@mingchen this is still an issue (see #260). Maybe @mbaechtold's migration should be added to django-cas-ng?

**Comment by mbaechtold** [comment]
I think this issue has been solved by the pull request https://github.com/django-cas-ng/django-cas-ng/pull/261. There's no need to add my workaround to `django-cas-ng`. It's a workaround we used to put into our projects, i.e. web applications built with Django and `django-cas-ng` as a dependency.
