### ISSUE TITLE
The login view doesn't support token auth

### ISSUE THREAD

**Issue by duoi** [mingchen/django-cas-ng#175]
**The issue**

The existing login view doesn't seem any flexibility after a successful login, it only does a `HttpResponseRedirect` to the `next_page` argument.

For example:
```
if is_user_authenticated:
    if settings.CAS_LOGGED_MSG is not None:
        message = settings.CAS_LOGGED_MSG % request.user.get_username()
        messages.success(request, message)
    return HttpResponseRedirect(next_page)
```

**A possible solution**

The view(s) are rewritten to be inheritable `class`-based views instead of `function`-based views. We move the action to being an overridable function call instead, with the default action of a `HttpResponseRedirect` to `next_page`, and also passing in the `user` object for flexibility.

For example:
```
def successful_login(user, next_page):
    return HttpResponseRedirect(next_page)

if is_user_authenticated:
    if settings.CAS_LOGGED_MSG is not None:
        message = settings.CAS_LOGGED_MSG % request.user.get_username()
        messages.success(request, message)
    return self.successful_login(user=request.user, next_page=next_page)
```

This opens up the window to have `successful_login` return `JSON` with an authentication token or anything else. 

For example
```
def successful_login(user, next_page):
    token = AuthToken.objects.create(user=user)
    response = HttpResponseRedirect(next_page)
    response.set_cookie(key='token', value=token)

    return response
```

EDIT: Added in a more realistic use-case

**Comment by duoi** [comment]
I'm happy to do this this weekend if it would be a welcomed addition. I'm currently doing this and just manually overriding the view altogether, but would like to see it upstream.

**Comment by mingchen** [comment]
PR is always welcome.

**Comment by duoi** [comment]
@mingchen I have the changes ready to go [here](https://github.com/duoi/django-cas-ng/tree/class-based-views), but going to wait on #176 first due to me wrongfully branching off that branch when I started.
