### ISSUE TITLE
django-cas-ng 3.6.0 AttributeError: module 'django_cas_ng.views' has no attribute 'login'

### ISSUE THREAD

**Issue by golways** [mingchen/django-cas-ng#189]
Hi,

Till today, I used django-cas-ng 3.5.10 in my django project and it worked fine. This morning, I upgraded to 3.6.0 and now I get this error:

  File "(Full path)\urls.py", line 28, in <module>
    path('accounts/login/', django_cas_ng.views.login, name='cas_ng_login'),
AttributeError: module 'django_cas_ng.views' has no attribute 'login'

Is there some thing to change in django-cas-ng configuration ?

I am using Python 3.7 (Windows 64bits) with some modules:

>pip list
Package               Version
--------------------- ----------
certifi               2018.10.15
chardet               3.0.4
Django                2.1.3
django-cas-ng         3.6.0
idna                  2.7
lxml                  4.2.5
pip                   18.1
psycopg2              2.7.6.1
pyasn1                0.4.4
pyasn1-modules        0.2.2
python-cas            1.4.0
python-ldap           3.1.0
pytz                  2018.7
requests              2.20.1
setuptools            40.6.2
six                   1.11.0
urllib3               1.24.1
virtualenv            16.1.0
virtualenvwrapper-win 1.2.5

>

Regards,
Franck

**Comment by golways** [comment]
I correctly added:

'django_cas_ng.middleware.CASMiddleware',

to MIDDLEWARE (not MIDDLEWARE_CLASSES  since I use Django 2.1)

**Comment by mingchen** [comment]
There was a PR #179 Class-based Login, Logout and Callback views, plus successful_login overridable method.

@duoi Could you take a look at this issue? It is related your PR.

**Comment by pix106** [comment]
in urls.py, replace django_cas_ng.views.login" with django_cas_ng.views.LoginView.as_view()

**Comment by golways** [comment]
Hi,
I also updated these two lines:

    path('accounts/logout/', django_cas_ng.views.LogoutView.as_view(), name='cas_ng_logout'),
    path('accounts/callback/', django_cas_ng.views.CallbackView.as_view(), name='cas_ng_proxy_callback'),

It works great, thanks !

Franck
