### ISSUE TITLE
CAS_USERNAME_ATTRIBUTE appears to not work

### ISSUE THREAD

**Issue by idwright** [mingchen/django-cas-ng#193]
django-cas-ng==3.6.0
I have the following configuration
CAS_VERSION = 3
 
 CAS_USERNAME_ATTRIBUTE = 'mail'
 CAS_APPLY_ATTRIBUTES_TO_USER = True
 CAS_RENAME_ATTRIBUTES = { 
      'familyName':'last_name',
      'givenName':'first_name',
      'mail':'email',
  }   

The created user has first_name, last_name and email all filled in correctly but is using the id returned from the CAS server instead of mail as the username

**Comment by luolin0313** [comment]
你django,python是什么版本啊，你配置CAS_VERSION = 3 不报错么
