### ISSUE TITLE
support next_page as LoginView and LogoutView kwargs

### ISSUE THREAD

**Issue by danizen** [mingchen/django-cas-ng#199]
Common practice for a generic view, like Login, is to accept *args, **kwargs.
Version 3.5.9 supports next_page as a kwargs, and my colleague hard codes kwargs in his url configuration so that "/docline/logout/" passes one next_page argument, and "/loansomedoc/logout/" passes another next_page argument.

My infrastructure library that wraps django_cas_ng broke his logout by passing *args, **kwargs to LogoutView.

**Comment by mingchen** [comment]
PR welcome

**Comment by danizen** [comment]
> PR welcome

Working on it...

**Comment by danizen** [comment]
@jdufresne, I had some interesting issues running isort in a local virtualenv (with virtualenvwrapper) instead of within the environment created by tox.  The thing is that isort recognized django_cas_ng as the local package, and so wanted to treat django_cas_ng absolute imports much as it would treat relative imports , e.g  from .utils import...

You may want to look at this and decide whether to change how that tox environment runs.   It is probably also more future proof to run the travis test for isort under Python 3.6 or something, as that is what most of us will use  for development.

I would change it myself, but my development environment has to be Windows 10 because I work for the federal government, and even if I can get a Mac, not all my django engineers can, so I stick to Windows 10 for their sake - someone needs to learn how to run `chcp 65001` so that UTF-8 code is OK!
