### ISSUE TITLE
cas usage issue

### ISSUE THREAD

**Issue by d0nezer0** [mingchen/django-cas-ng#22]
Can you leave a email please?
I have a question , hope you can help.
Thanks a lot.

**Comment by mingchen** [comment]
Just leave your question here.

**Comment by d0nezer0** [comment]
OK, here is my question.
I use the django-cas-ng as the client .
When I logout the site, I also logout from the server, but  the other client sites didn't logout cause they have their own cookies.
Now I want to fix this issue. I tried to get a logout func for all the loggined sites in the logout clicked site.
Am I right?
what did you do with this?

**Comment by mingchen** [comment]
Sounds single sign out.
Check out CAS protocol for detail. The implement ion should based on CAS protocol.
http://jasig.github.io/cas/development/protocol/CAS-Protocol.html

**Comment by d0nezer0** [comment]
It's helpful, thanks a lot.

**Comment by mingchen** [comment]
You are welcome.
