### ISSUE TITLE
Django.utils.six deprecated in Django version 3.0.0

### ISSUE THREAD

**Issue by blwh** [mingchen/django-cas-ng#224]
`django.utils.six` is used in `utils.py`, so this package does not work for the newest Django version 3.0.0 at the moment.

Solution: Stay at v 2.2.7.

**Comment by ityoung** [comment]
@blwh Use master branch,

```
pip install https://github.com/mingchen/django-cas-ng/archive/master.zip
```

**Comment by mingchen** [comment]
Please use 4.0.0 release
