### ISSUE TITLE
CAS 3.4 + SAML

### ISSUE THREAD

**Issue by ramonrdm** [mingchen/django-cas-ng#24]
Hello,
I'm trying to use django-cas-ng with a CAS3.4 more SAML server.
The django-cas-ng version 3 does not pull the SAML information.
The django-cas-ng CAS_2_SAML_1_0 version does not pull the CAS user.
How can I do?
I am trying to merge the methods without success.

**Comment by mingchen** [comment]
Try to look at django_cas_ng/backends.py _verify_cas2_saml()
set break point or add log to trace what happened.

**Comment by ramonrdm** [comment]
I have found that the attribute name was not received by the SAML "uid".
in my case the attribute is "idPessoa"
I changed the method code "_verify_cas2_saml" to:
         success = tree.find ('.//' + SAML_1_0_PROTOCOL_NS + 'StatusCode')
         if success is not None and success.attrib ['Value'] == 'samlp: Success':
             # User is validated
             attrs = tree.findall ('.//' + SAML_1_0_ASSERTION_NS + 'Attribute')
             is at in attrs:
                 attributes [at.attrib ['AttributeName']] = at.find (SAML_1_0_ASSERTION_NS + 'AttributeValue'). text
         return attributes ['login'], attributes

Django-cas-ng works with CAS3.4!
Thank you!

**Comment by mingchen** [comment]
You are welcome.

**Comment by edouard-lopez** [comment]
I reckon you can use the setting `CAS_USERNAME_ATTRIBUTE` present since b9ab5ac to achieve what you want to do.

First, install a version that have this setting:

```sh
# default
pip install django-cas-ng
# or from git latest version
pip install --upgrade git+https://github.com/mingchen/django-cas-ng.git 
```
Then set in _settings.py_
```py
CAS_USERNAME_ATTRIBUTE = 'idPessoa'
```

**Comment by ramonrdm** [comment]
Very good!
I will use in new version of the software!
Thanks!

**Comment by mingchen** [comment]
You are welcome. Thanks for contribution.
