### ISSUE TITLE
'Module_six_moves_urllib_parse' object has no attribute 'urlencode'

### ISSUE THREAD

**Issue by ramonrdm** [mingchen/django-cas-ng#25]
Hi,
I use Django 1.6.1 in server
and get error: 
'Module_six_moves_urllib_parse' object has no attribute 'urlencode'

**Comment by rrignier** [comment]
Hello, Same problem with my Pydev environement in 1.6.1.
I have updated Six with `pip install --ugprage six` to 1.9.0, but still same error.

On Same host, with django 1.7.4  part of my Linux Mint 17 system, I have no issues.

**Comment by ramonrdm** [comment]
Thank you!
I have updated Django to 1.7.4
is work!
