### ISSUE TITLE
Request to make pipermerriam (me) a contributor

### ISSUE THREAD

**Issue by pipermerriam** [mingchen/django-cas-ng#35]
I put a lot of work into getting this project backed by a test suite as well as improving many parts of the codebase.  I would like to request being added as a contributor to this project.

**Comment by mingchen** [comment]
Definitely! You are already in credits list.
Feel free to send pull request if you like others.

**Comment by pipermerriam** [comment]
Sorry, I think my intention may have been mis-understood.  I'm hoping
you'll add me as a contributor on the github project which gives privileges
like merge permission.  Not the list of people in the credits list.

**Comment by mingchen** [comment]
I have added you to Collaborators. You are very welcome to contribute this project.
