### ISSUE TITLE
Factor out python library?

### ISSUE THREAD

**Issue by evgenyfadeev** [mingchen/django-cas-ng#45]
Is it possible to create the base python library for the CAS clients without being tied to Django and have a separate module for Django using the library instead of all being together?

p.s. started working on this. I need to create CAS authentication for Askbot, and would like to use just the purely cas-related code that is available in django-cas-ng and create the django binding custom for Askbot due to the way how authentication is implemented there.

**Comment by evgenyfadeev** [comment]
Here is a PR https://github.com/mingchen/django-cas-ng/pull/46

All tests pass, the factored out code is in the file https://github.com/ASKBOT/django-cas-ng/blob/13dad5085a513fbc68f118b03e9423266ed82bd2/django_cas_ng/cas.py

**Comment by mingchen** [comment]
It's a great idea to make CAS part independently. I created a [dedicate org](https://github.com/python-cas) and invited you as owner. An empty repo [python-cas](https://github.com/python-cas/python-cas) also created, you can feel free to push code to this repo.

Thank you again for you contribution.
