### ISSUE TITLE
Latest code with Django 1.8

### ISSUE THREAD

**Issue by bhargu** [mingchen/django-cas-ng#49]
One thing to note - your code now uses models. So shouldn't you update the doc to add the app in the installed apps list? My test case was throwing errors before I noticed this. 

Also
- ProxyGrantingTicket.user foreign key to settings.AUTH_USER_MODEL
- ProxyGrantingTicket.date = models.DateTimeField(auto_now_add=True)
- SessionTicket.session = models.OneToOneField(Session, related_name="+")

Without these changes, Django 1.8 was throwing errors and warnings (about the last case).

**Comment by nitmir** [comment]
I'll look at this soon (quite busy now) to make the the ProxyGrantingTicket session backend agnostic (here it suppose you use the database backend), but yes if you intend to use PGT (setting the CAS_PROXY_CALLBACK and callback view), django_cas_ng should definitely be added to INSTALLED_APPS and ./manage.py syncdb called for django_cas_ng to be able to store the PGT.
