### ISSUE TITLE
German Translations for Login Messages

### ISSUE THREAD

**Issue by kavdev** [mingchen/django-cas-ng#58]
I'm don't feel like downloading an editor for this, so here are the relevant bits:

```python
#: __init__.py:23
#, python-format
msgid "Login succeeded. Welcome, %s."
msgstr "Sie wurden reibungslos angemeldet. Willkommen, %s."

#: __init__.py:24
#, python-format
msgid "You are logged in as %s."
msgstr "Sie sind als %s angemeldet."
```

**Comment by mingchen** [comment]
Awesome.
Can you send a pull request ?

**Comment by kavdev** [comment]
Possibly later today. I don't want to download a .po editor, so I'll look into finding a free online resource. If I can't find one, I'll just add in the file and edit the metadata by hand.
________________________________

**Comment by nitmir** [comment]
@kavdev I made a pull request (#59) out of your translation.

**Comment by nitmir** [comment]
In fact, I wonder if including .mo in the repository is really pertinent.
Maybe would it be better to add the command `django-admin compilemessages` in the Makefile

**Comment by mingchen** [comment]
agreed, .mo file should not be in repository.

**Comment by kavdev** [comment]
Cool.
