### ISSUE TITLE
proxy-friendly modifications

### ISSUE THREAD

**Issue by manelclos** [mingchen/django-cas-ng#60]
Hi,

I'll love to update my projects to use django-cas-ng, would you accept pull requests for the following modifications?

It seems urllib ignores the no_proxy environment variable, so I switched to using requests, example here:
https://github.com/manelclos/django-cas2/commit/b2f25b3dafb1a048e66372d862fdc3daabdfd399

When using proxied connections (:80 to :8080) the hostname will change to have :8080 appended. I added a configuration option so this can be set in settings.py:
https://github.com/manelclos/django-cas2/commit/4f570c5067e9e1e0c3c9255adc22729b4f1041d6

Please let me know what you think.

Thanks!

**Comment by mingchen** [comment]
Sure. please also update README to document how to use it.

**Comment by danizen** [comment]
I'd suggest that you follow mingchen's convention of putting defaults for the settings in `django_cas_ng/__init__.py`.   This was a revelation to me about how to get settings defaults done, though in future django apps I guess these sorts of things are supposed to be in `apps.py`.

**Comment by bgroff** [comment]
This change also means that requests is now a requirement of the project. I normally think that requests is easier to use than urllib, however urllib is in the standard library. So, there are a few things to consider:

1. Add requests as a dependency - easiest, but not ideal imho as not everyone has this by default.
2. Attempt to import requests, and use requests if the package installed.
3. Have a setting somewhere that defaults to use urllib, but can use requests if the setting is set and requests is installed.

IMHO option two is best, but as far as configurability goes 3 is the preferred solution.

**Comment by mingchen** [comment]
I am ok to add dependency to ``requests``, it is much more easier than ``urllibx``.

**Comment by mingchen** [comment]
closed due to in-active.
