### ISSUE TITLE
Use transifex to handle internationalization?

### ISSUE THREAD

**Issue by bgroff** [mingchen/django-cas-ng#62]
Just wanted to get a feel if anyone was interested in using https://www.transifex.com/django-cas-ng/ as a way to translate the strings in the project? This web interface allows one to click on the origin string, and add a translation through the web interface. This should make it a little easier for people that do not want to dig into the code to still help translating.

I know this is a small project and most people doing the translations are also developers, so maybe this is not needed.

**Comment by mingchen** [comment]
It is a great idea!

How easy to setup a transifex translation project ?
Can it be integrate with gitbub seamlessly ?

**Comment by bgroff** [comment]
I think we can integrate the two, I will look more into soon.

**Comment by bgroff** [comment]
It seems that people updating the PO files is probably easier than setting this up. I have not had time to deal with the integration, so I am closing this ticket for now.
