### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bgroff** [mingchen/django-cas-ng#64]
Hey Everyone,
So I noticed that in commit: ddd0ee2 the model changed the name of session to session_key. I think this will break anyones install that had the tables built previous to this commit. I think that we should ship migrations with the upcoming release and provide documentation on how to run them. I think I have a little bit of time to try and put this together if people think it is worth the effort.

If we do not want to provide migrations, I think the name should be changed back to session to avoid having to edit the database by hand.

**Comment by nitmir** [comment]
I fact you can just delete the old tables in database as it only contain temporary data and perform and ./manage.py syncdb.

**Comment by bgroff** [comment]
Very true, maybe we should add a note somewhere? I don't think it would make sense in the readme as the models have only existed for a short period of time, so this change probably will not effect many people. Any thoughts?

**Comment by nitmir** [comment]
It is already in the README : 
> Run ./manage.py syncdb to create Single Sign On and Proxy Granting Ticket tables. On update you  can just delete the django_cas_ng_sessionticket table and the django_cas_ng_proxygrantingticket 
 before calling ./manage.py syncdb

maybe should it be somewhere more visible like and UPDATE or CHANGELOG file ?

**Comment by bgroff** [comment]
Ah I see. Maybe adding a CHANELOG file would be useful. I just see people that are not particularly technical updating to 3.4.2 running syncdb, then updating to 3.4.3 (or whatever it may be called), and then their application crashes and they don't know why.

**Comment by mingchen** [comment]
There is changelog file to document changes for every release. https://github.com/mingchen/django-cas-ng/blob/master/docs/changelog.rst Could you some body update it for up coming release ?

**Comment by bgroff** [comment]
OK I will have a pull request done today. nitmir, could you look at 36681601c3715574cbf22cf24054bb9abc629db9 to make sure I did not break the callback code for single sign out?

**Comment by nitmir** [comment]
I think 3668160 is ok.
