### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by wcc526** [mingchen/django-cas-ng#71]
from cas import CASClient
ImportError: cannot import name CASClient

**Comment by nitmir** [comment]
python-cas==1.1.0 is listed in the requirement.txt file
It is available via pip or here https://github.com/python-cas/python-cas

**Comment by wcc526** [comment]
I have try install python-cas,but it is still failure. Does it django-cas-ng is a runable project?

**Comment by nitmir** [comment]
I run it on production without any troubles. I've installed both python-cas and django-cas-ng from git repository with a ```sudo make install```.
How are you installing it ? from pip ?

**Comment by VDaric** [comment]
Hello,

I installed django-cas-ng with pip.

I first got the same error as wc526 : ImportError: cannot import name CASClient.
After a modification in django_cas_ng/utils.py file (#72). [replacing "from cas import CASClient" by
"from caslib import CASClient"] and I installed  caslib (from pip) but I  am still having an error.

This time it seems to be caslib related problem :
...lib/python3.4/site-packages/caslib/__init__.py", line 21, in <module>
from cas_dance import *
ImportError: No module named 'cas_dance'

Here is (a part of) my pip freeze output:
caslib==0.3.1
django-cas-ng==3.5.1
python-cas==1.1.0

I am running Django==1.8.6 with Python3.4.3.

**Comment by nitmir** [comment]
This project do not use `caslib`. `python-cas` provide the cas module used by the statement `from cas import CASClient` https://github.com/python-cas/python-cas/blob/master/cas.py#L26

```
┬────────────────────────────────┬──────────────────────────────────────────────
│ 16:52, jeudi 19 novembre 2015  │
└────────────────────────────────┘

─( 16:52:30 )─< ~ >───────────────────────────────────────────────────────[ 0 ]─
valentin@nashi $ mktemp -d
/tmp/tmp.LcmGsEc5y4
─( 16:52:32 )─< ~ >───────────────────────────────────────────────────────[ 0 ]─
valentin@nashi $ virtualenv /tmp/tmp.LcmGsEc5y4
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/tmp.LcmGsEc5y4/bin/python2
Also creating executable in /tmp/tmp.LcmGsEc5y4/bin/python
Installing setuptools, pip...done.
─( 16:52:38 )─< ~ >───────────────────────────────────────────────────────[ 0 ]─
valentin@nashi $ . /tmp/tmp.LcmGsEc5y4/bin/activate
─( 16:52:46 )─< ~ >───────────────────────────────────────────────────────[ 0 ]─
valentin@nashi $ pip install python-cas django-cas-ng
Downloading/unpacking python-cas
  Downloading python-cas-1.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-GbfB_r/python-cas/setup.py) egg_info for package python-cas
    WARNING: '.' not a valid package name; please use only.-separated package names in setup.py
    
    package init file '__init__.py' not found (or not a regular file)
Downloading/unpacking django-cas-ng
  Downloading django-cas-ng-3.5.1.tar.gz
  Running setup.py (path:/tmp/pip-build-GbfB_r/django-cas-ng/setup.py) egg_info for package django-cas-ng
    
Downloading/unpacking six (from python-cas)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking Django>=1.5 (from django-cas-ng)
  Downloading Django-1.8.6-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Installing collected packages: python-cas, django-cas-ng, six, Django
  Running setup.py install for python-cas
    WARNING: '.' not a valid package name; please use only.-separated package names in setup.py
    package init file '__init__.py' not found (or not a regular file)
    
  Running setup.py install for django-cas-ng
    
Successfully installed python-cas django-cas-ng six Django
Cleaning up...
─( 16:53:03 )─< ~ >────────────────────────────────────────────────────────────────────────────────[ 0 ]─
valentin@nashi $ python -c "import cas; print cas.__file__"
/tmp/tmp.LcmGsEc5y4/local/lib/python2.7/site-packages/cas.pyc
```

**Comment by nitmir** [comment]
However, it could be nice to have pip to auto install python-cas on django-cas-ng install.
@mingchen maybe add python-cas in the install_requires of setup.py ?
I do not known how pip handle dependencies.

**Comment by bgroff** [comment]
If python-cas is in the install_requires, pip should grab and install it when installing django-cas-ng. I agree that python-cas should be installed when installing django-cas-ng.

**Comment by mingchen** [comment]
Added python-cas to install_requires.

**Comment by wcc526** [comment]
@VDaric I suggest you use the https://bitbucket.org/cpcc/django-cas this repo,It's more stable,If you have any problem you can contact with me by gmail.   wcc526#gmail.com

**Comment by nitmir** [comment]
@wcc526 @VDaric  It will depend of the features you needs. Among those supported by django-cas-ng not supported by django-cas : 
  * support of CAS 3.0: i.e. be able to use attributes transmitted by the CAS
  * support of Single Sign Out (login-out from the CAS (from anywhere) will cause a logout from django)
  * be able to emit proxy ticket to allow django to login to some backends (I use it to login to an XMPP server in prebind mode and to users ftp accounts with a web interface)

**Comment by nitmir** [comment]
Also note that the split between django-cas-ng and python-cas is very recent (it was a single project until 2c046f199d40f98e106bfedea2d64f3432a87191)  thus it's not odd the see some packaging issues.

Thanks for reporting.

**Comment by VDaric** [comment]
Everything works nice now. I just "pip installed" python-cas.

Thanks !

**Comment by imradhakrishnan** [comment]
I am using Django 1.11.6 with django-cas-ng 3.5.1.  I am still facing this issue. Any help is appreciated. Thanks!

**Comment by johnnyz** [comment]
I am using DJango 1.11.6 with cas-ng 3.5.1 and python-cas 1.2 and also still have thus issue. 

Imradhakrishnan - did you find a solution?

**Comment by mhcesped** [comment]
I was having this problem too. To fix it I had to uninstall python-cas, django-cas-ng and django-cas-client, then I re-installed django-cas-ng and it was solved ... surely there is some incompatibility with django-cas-client.

Hope this help.

**Comment by caixinglobus** [comment]
> I was having this problem too. To fix it I had to uninstall python-cas, django-cas-ng and django-cas-client, then I re-installed django-cas-ng and it was solved ... surely there is some incompatibility with django-cas-client.
> 
> Hope this help.

helps a lot!
