### ISSUE TITLE
AnonymousUser after login

### ISSUE THREAD

**Issue by shacker** [mingchen/django-cas-ng#81]
In my template:

```
    {% if not user.is_authenticated %}
        Login button links to CAS server
     {% endif %}
```
Under v 3.4.2 this works perfectly. 

After upgrading to 3.5.2, the login button still displays after successful login. If I render {{user}} in the template, the user is AnonymousUser after login (same if I `print(request.user)` in the view). If this user now clicks the Login button a second time, CAS recognizes them as pre-authenticated and logs them in immediately. 

It seems like the actual django login() call is no longer being invoked. 

Downgrading for now.

**Comment by shacker** [comment]
Additional info: I actually use django_cas_ng on two sites, and this problem is only happening on one  of them.  

Python 2.7 + Django 1.8.2 = broken
Python 3.5  + Django 1.9.1 = working

**Comment by nitmir** [comment]
working fine with v3.5.3 + python 2.7 + Django 1.7.7

**Comment by shacker** [comment]
Hmm, interesting. It definitely broke for me on update. Our implementation is very straightforward - nothing fancy. The only settings I'm using are:

```
CAS_SERVER_URL = 'https://cas.ourdomain.edu/cas/login'
CAS_ADMIN_PREFIX = '/admin'
CAS_LOGOUT_COMPLETELY = True
CAS_REDIRECT_URL = '/'
```

If this is a result of a bug elsewhere in our project code, I don't know where to begin to look. Ideas?

**Comment by nitmir** [comment]
right now, I really don't known. There is a lot of changes since v3.4.2 (the main one I think being putting all CAS logic in a external lib https://github.com/python-cas/python-cas). I'll try tomorrow on Django 1.8.2 to see if I can reproduce the bug.

**Comment by nitmir** [comment]
sorry but I cannot reproduce
```
mkdir /tmp/testcas
virtualenv /tmp/testcas
. /tmp/testcas/bin/activate
pip install Django==1.8.2
pip install django-cas-ng
cd /tmp/testcas/
django-admin startproject testproject
# setup django-cas-ng by editing testproject/settings.py and testproject/urls.py
django-admin startapp testapp
# add testapp to testproject/settings.py and testproject/urls.py and setup a trivial view
```

My trivial view is
```
from django.contrib.auth.decorators import login_required

@login_required
def test(request):
    raise ValueError("username: %s is auth %s" % (request.user, request.user.is_authenticated()))

```
And it effectively raise my current username and True and not AnonymousUser.
for info : 
```
$ pip freeze
Django==1.8.2
argparse==1.2.1
django-cas-ng==3.5.3
python-cas==1.1.0
six==1.10.0
wsgiref==0.1.2
```

Just note that your `CAS_SERVER_URL` should probably be `'https://cas.ourdomain.edu/cas/'` without the `login` but I do not think it really matter as I have tested too with a `/login` in my CAS url and it worked just fine…

**Comment by shacker** [comment]
Interesting. Well, thank you very much for investigating! I'm not sure where to begin troubleshooting this one, but at this point it appears to  definitely be somehow related to my codebase. I'll close this and leave a comment in the future when I figure it out. Thanks.

**Comment by wemeetagain** [comment]
I had the same issue,
python 2
Django 1.8
django-cas-ng 3.5.3

Unsure of what _exactly_ the problem was, but commenting/removing the following lines fixed the issue: https://github.com/mingchen/django-cas-ng/blob/master/django_cas_ng/views.py#L64-65

Not saying its a good idea, but it worked for me.
