### ISSUE TITLE
Application session keys is recreated in django_cas_ng/views

### ISSUE THREAD

**Issue by Chingo** [mingchen/django-cas-ng#83]
Hi All,

I found the application session keys (request.session.session_key) is recreated at the django_cas_ng/views line: 65. This causes the session data get cleared of a  successful login (django_cas_ng/views line: 63). This leads to a second successful CAS login is required to acquire a valid application session. If CAS SSO is disable, users have to login CAS twice to get a valid application session. 

After I temporarily modify the "django_cas_ng/views line: 65" to "**request.session.save()**", this issue seems fixed. 

Does anyone have any ideas for this issue? Any comment is appreciated! 

-Chingo

**Comment by bgroff** [comment]
@mingchen does the #96 merge fix this issue as well?

**Comment by mingchen** [comment]
closed due to in-active.
