### ISSUE TITLE
Lowercase usernames on authentication

### ISSUE THREAD

**Issue by shacker** [mingchen/django-cas-ng#86]
Django allows usernames 'joe'  and 'JOE' to exist simultaneously. There is an [old ticket](https://code.djangoproject.com/ticket/2273) about this, but it's marked `won't fix`.

We have a user import script that brings in lots of users in advance. As a result of this script run, 'joe' might already exist in the system.

But then, the user might come along and log in as 'JOE'.  CAS accepts this, and passes it to django-cas-ng, which happily creates a 2nd account for the same person. 

There are various AUTHENTICATION_BACKEND fixes posted out there for this problem, but of course we're already using django_cas_ng as the backend, so that's not an option.

We'll ask to have our central CAS login page modified so that it lowercases usernames on submit. But it would be great if django-cas-ng could also have an option to lowercase the username passed to it from CAS, or to prevent creation of usernames that already exist with different cases.

**Comment by mingchen** [comment]
If you would like to send a pull request with new option to convert username that would be great.

**Comment by nitmir** [comment]
Note that this can also be resolve by telling the CAS to use a particular field as username (for instance, the field username in your database) and not the name entered by the user on login. For instance:
```xml
                <property name="resultAttributeMapping">
                        <map>
                                <entry key="aid" value="aid" />
                                <entry key="uid" value="user" />
                […]
                    <bean class="org.jasig.cas.services.RegisteredServiceImpl">
                        <property name="id" value="4" />
                        <property name="name" value="Intranet 2" />
                        <property name="description" value="L'intranet 2 du Cr@ns" />
                        <property name="serviceId" value="https://intranet2.crans.org/**" />
                        <property name="evaluationOrder" value="4" />
                        <property name="usernameAttribute" value="user" />
                        <property name="allowedAttributes">
                            <list>
                                <value>login_mail</value>
                                <value>prenom</value>
                                <value>nom</value>
                                <value>cn</value>
                                <value>user</value>
                            </list>
                        </property>
                    </bean>
```

Here the CAS will transmit as username the value of `user` witch is the value of `uid` in our ldap database, where the case is enforced.
