### ISSUE TITLE
Performing schemamigration produces an error

### ISSUE THREAD

**Issue by tayapski** [mingchen/django-cas-ng#90]
I just recently downloaded django-cas-ng 3.5.4 and trying to integrate it with Django 1.6.1. I was doing the migration using schemamigration when I got this error.

south.exceptions.UnknownMigration: Migration 'django_cas_ng:0001_initial' probably doesn't exist.

I checked and it was there. What should I do next? Did I miss a step?

**Comment by bgroff** [comment]
Django 1.6 does not include the migrations framework. You will need to use Django 1.7+ or you can try just using syncdb and see how far that gets you. I would highly suggest moving to a more recent version of Django though. The 1.8 release is an LTS and is supported to 2020 (I think).

**Comment by bgroff** [comment]
This issue has not been updated in several months, are you still experiencing issues? I would suggest closing this issue if no action is taken.

**Comment by tayapski** [comment]
I found a workaround using South. Closing the issue now.
