### ISSUE TITLE
Update middleware to accept named url patterns for LOGIN_URL

### ISSUE THREAD

**Issue by danizen** [mingchen/django-cas-ng#92]
Issue is that LOGIN_URL is supposed to handle named url patterns - https://docs.djangoproject.com/en/1.9/ref/settings/#login-url

Quite by accident, I discovered it doesn't by trying to set the LOGIN_URL to "casauth:sigin" in a Django app that I layer on top of django-cas-ng.

I will supply a pull request.

**Comment by mingchen** [comment]
closed due to in-active.
