### ISSUE TITLE
single sign out

### ISSUE THREAD

**Issue by SolarisYan** [mingchen/django-cas-ng#94]
hi:
    how to set slo with cas server 4.2, i do this but can't achive that . thx

**Comment by danizen** [comment]
Maybe your /cas/logout URL on the CAS server isn't doing the right thing on its own?

I suggest you use a tool like the Chrome extension Live Http Headers to monitor the logout process and verify it is going correctly, removing the cookies properly at each location.

Even once you get it working, recall that logout is complicated.   If you have already authenticated to two sites that share the same CAS server, then logout from one site may not log you out from the other site.   It depends on the domains on the cookies which indicate that hold the successful authentication.   In `django_cas_ng`, that is integrated into the Django session.

However, I've had no difficulties with `CAS_LOGOUT_COMPLETELY` working, and it is enabled by default.

**Comment by nitmir** [comment]
@danizen  SLO is a CAS server "back channel communication" process. Upon user logout, the CAS send a request to each authenticated site to tell them that the user just logout (with the ticket value as parameter).

@SolarisYan django-cas-ng support SLO out of the box, you should check if your CAS server is sending SLO request: a POST request with the 'logoutRequest' parameter containing a SLO XML request (as phpCAS do: https://github.com/Jasig/phpCAS/blob/9376b31c8c51180e918efa11470f9d928cdc43ef/source/CAS/Client.php#L1720)
