### ISSUE TITLE
Django 1.10 upgrade forced by upgrade

### ISSUE THREAD

**Issue by shacker** [mingchen/django-cas-ng#95]
I was on version 3.4.2 with Django v1.9.x, and ran:

`pip install --upgrade django-cas-ng==3.5.2`

and found my Django version was forced up to 1.10. I was able to downgrade it manually, but that probably should not have happened automatically, right?

**Comment by shacker** [comment]
I believe this is a result of this line in setup.py:

`install_requires=['Django >= 1.5', 'python-cas==1.1.0'],`

The python [packaging docs](https://packaging.python.org/requirements/) say:

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

I would venture that it's safer not to specify Django at all there (who is going to try and install cas-ng without a working Django?) It's true that you don't want them using versions lower than 1.5, but that can just be in the documentation.

**Comment by danizen** [comment]
Isn't this just how pip works?    I suggest this not be fixed.   `django-cas-ng` does depend on `django`.

**Comment by shacker** [comment]
It's only working this way because we're making it work this way. Upgrading a dependency should *never* force an unrequested upgrade of the entire framework.

**Comment by shacker** [comment]
I can `pip install` django reusable apps all day but they don't force an upgrade of Django itself. This is an anomaly.

**Comment by cmurtaugh** [comment]
Hey @shacker - I think you just want to leave out the `--upgrade` in your original `pip` command:

`pip install django-cas-ng==3.5.2` 

That will upgrade your installed version of django-cas-ng to 3.5.2 if you have an older one (or downgrade it if you have a newer one), but it won't upgrade the dependencies as long as what you have installed meets the `install_requires` condition.

**Comment by shacker** [comment]
@cmurtaugh You are correct - I misunderstood how `--upgrade` works. In fact the [documentation](https://pip.pypa.io/en/stable/user_guide/#only-if-needed-recursive-upgrade) says:

> `pip install --upgrade` is currently written to perform an eager recursive upgrade, i.e. it upgrades all dependencies regardless of whether they still satisfy the new parent requirements.

and

> Running `pip install --upgrade SomePackage` would upgrade SomePackage and AnotherPackage despite AnotherPackage already being satisfied.

I tested by downgrading cas-ng and then upgrading it again without the `--upgrade` flag and sure enough, it worked perfectly:

`Requirement already satisfied (use --upgrade to upgrade): Django>=1.5`

Thanks.

**Comment by mingchen** [comment]
Fixed by pull request #97 and #99
